#!/bin/bash
#simple functions
shist ()
{
  history | grep $1 | uniq
}
shis() 
   {
   history | cut -c 1-7 --complement | sort | uniq | grep $1 
   }
manv ()
{
   man $1 | vim -
}
hism()
{
   echo  "fd -H -I --changed-within 5min"
fd -H -I --changed-within 5mins
}

cha() {
   fdfind -H -I --changed-within $1mins | rg -v '\.git' | rg -v '\theia'
}

vdiff () {
    if [ "${#}" -ne 2 ] ; then

        printf "vdiff requires two arguments"
        echo "  comparing dirs:  vdiff dir_a dir_b"
        echo "  comparing files: vdiff file_a file_b"
        return 1
    fi

    local left="${1}"
    local right="${2}"

    if [ -d "${left}" ] && [ -d "${right}" ]; then
        vim +"DirDiff ${left} ${right}"
    else
        vim -d "${left}" "${right}"
    fi
}
function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}
alias lln="ls -lhtr  --time-style long-iso | tac | cat -n | tac | sed -s 's/^\s*\([0-9]*\)\s*\(.*\)/[\1]  \2 [\1]/'g && pwd"
function lf() {
    if [ "x${1}" == "x" ]
    then
        n=1 
    else
        n="${1}"
    fi  
    ls -rt1 | tail -n ${n} | head -n 1
}
