#!/bin/bash
#simple functions
shist ()
{
  history | grep $1 | uniq
}
shis() 
   {
   history | cut -c 1-7 --complement | sort | uniq | grep $1 
   }
manv ()
{
   man $1 | vim -
}
hism()
{
   echo  "fd -H -I --changed-within 5min"
fd -H -I --changed-within 5mins
}

cha() {
   fdfind -H -I --changed-within $1mins | rg -v '\.git' | rg -v '\theia'
}

vdiff () {
    if [ "${#}" -ne 2 ] ; then

        printf "vdiff requires two arguments"
        echo "  comparing dirs:  vdiff dir_a dir_b"
        echo "  comparing files: vdiff file_a file_b"
        return 1
    fi

    local left="${1}"
    local right="${2}"

    if [ -d "${left}" ] && [ -d "${right}" ]; then
        vim +"DirDiff ${left} ${right}"
    else
        vim -d "${left}" "${right}"
    fi
}

